- name: message to say
  debug:
    msg: "Hello {{ item.container_name }}"
  register: nicu
  with_items: "{{ containers }}"

- name: what is nicu
  debug:
    msg: "My ID is {{ item.id }}"
  when: item.container_name == httpd
  with_items: "{{ containers }}"

- name: a list of msg
  debug:
    msg: |
        {{ item.container_name }}
        {{ item.version }}
        {{ item.id }}
  with_items: "{{ containers }}"